# See https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/projects"
    schedule:
      interval: "weekly"
      day: wednesday
    open-pull-requests-limit: 2
    versioning-strategy: increase
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    reviewers:
      - process-analytics/pa-collaborators

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: wednesday
    open-pull-requests-limit: 2
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore(gha)"
    reviewers:
      - process-analytics/pa-collaborators
