name: 'Build Setup'
description: 'Setup node and install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - name: Install dependencies
      uses: bahmutov/npm-install@v1
      with:
        install-command: npm ci --prefer-offline --audit false
